### ISSUE TITLE
Newlines in sort columns break deserialization

### ISSUE THREAD

**Issue by acarapetis** [djrobstep/sqlakeyset#26]
If a query is ordered by a text-type column and the values stored in this column include newlines, parsing the resulting bookmarks results in markers cut off after the newline:

```python
>>> from sqlakeyset.results import s
>>> s.unserialize_values(s.serialize_values(('hello\nthere', 12)))
['hello']
```

**Comment by acarapetis** [comment]
The culprit here is that we're using `lineterminator=''` in the `csv.writer`, so it doesn't escape newlines since they shouldn't have any special meaning; but `csv.reader` is [hard-coded to treat newlines as line terminators](https://docs.python.org/3.6/library/csv.html#csv-fmt-params).

**Comment by asing1** [comment]
One way to avoid this would be to escape the \r and \n characters during serialisation itself e.g 'hello\\nthere' and after deserialisation we can convert it back to normal form 'hello\nworld'
I can work on this if this sounds good and nobody is working on it.
