### ISSUE TITLE
No attribute 'is_single_entity' with Flask-SQLAlchemy

### ISSUE THREAD

**Issue by Ryanb58** [djrobstep/sqlakeyset#29]
Hello, I am trying to use this library with an existing project and it seems that my `q` does not have the `is_single_entity` attribute that is being used here:

https://github.com/djrobstep/sqlakeyset/blob/master/sqlakeyset/paging.py#L22

My models inherit from `db.Model` which comes from Flask-SQLAlchemy. When I run `type(q)` it returns `<class 'flask_sqlalchemy.BaseQuery'>` which I located here:

https://github.com/pallets/flask-sqlalchemy/blob/master/src/flask_sqlalchemy/__init__.py#L416

it looks like it inherits from `orm.Query` which is here:

https://github.com/sqlalchemy/sqlalchemy/blob/master/lib/sqlalchemy/orm/query.py#L71

Which appears to have the desired `is_single_entity` attribute.. does anyone have any ideas as to why that property wouldn't be propagating through the inheritance hierarchy to my Model?

**Comment by acarapetis** [comment]
What versions of sqlalchemy and sqlakeyset are you using? This seems like the dependency issue that was fixed by #23 .

**Comment by Ryanb58** [comment]
Good catch! 

My app was using the following.  
```
SQLAlchemy==1.3.5
sqlakeyset==0.1.1579837191
```

Once I updated SQLAlchemy to above 1.3.11 then it started working.

Thank you @acarapetis
