### ISSUE TITLE
check __table__.name instead of __tablename__ in orm_placemarker_from_row

### ISSUE THREAD

**Issue by arabidopsis** [djrobstep/sqlakeyset#3]
line 74 in paging.py might be more robust with the check as:

            if entity.__table__.name == ocol.table_name:

Since the entity will (eventually) have a `__table__` attribute but might not have a `__tablename__` one.
see: http://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/table_config.html#using-a-hybrid-approach-with-table

**Comment by djrobstep** [comment]
Makes sense. I'll fix this up when I can, or happy to accept a pull request if you're keen.

**Comment by djrobstep** [comment]
fixed by https://github.com/djrobstep/sqlakeyset/commit/050c161e07e300e3c56ef95f510fda38f37f99b0
