### ISSUE TITLE
Do not work with Python prior to 3.6 because fstring is used

### ISSUE THREAD

**Issue by inkhey** [djrobstep/sqlakeyset#32]
Hello.
I'm getting error using this library with python 3.5 due to the usage of fstring.
It will be better to either not use fstring or clearly documentate that python 3.6+ is required.

```
../../../virtualenv/python3.5.7/lib/python3.5/site-packages/sqlakeyset/paging.py:6: in <module>
    from .columns import parse_clause, find_order_key
E     File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/sqlakeyset/columns.py", line 43
E       f"Ordering by nullable column {x} can cause rows to be "
E                                                              ^
E   SyntaxError: invalid syntax
```

**Comment by acarapetis** [comment]
Whoops, my bad! I'll get a fix out today.

**Comment by acarapetis** [comment]
@inkhey The offending f-string has been removed and a [new version](https://pypi.org/project/sqlakeyset/1.0.1595476224/) has been published to PyPI - let us know if you have any other issues! Thanks for your report.

**Comment by inkhey** [comment]
@acarapetis Thank you for this patch ! I just tried it and it's working perfectly for the part i tried.
