### ISSUE TITLE
Explicit error when unserialization failed ?

### ISSUE THREAD

**Issue by inkhey** [djrobstep/sqlakeyset#34]
It will be nice to have an explicit error when unserialization failed.
Using serialization for http api, it's possible that client send uncorrect bookmark page string, which
return different python unexplicit error, which are difficult to catch correctly (get distinction between broken code and incorrect bookmark string from client).

Here, my workaround to handle this case directly in my own code (my software use `page_token` naming):
```
try:
    a = unserialize_bookmark(page_token)
except Exception as e:
    raise InvalidPageToken('page token given is not valid')
return get_page(query, per_page=count, page=page_token or False)
```

**Comment by acarapetis** [comment]
@inkhey: I've pushed a new release to PyPI. You should now be able to catch the exception `sqlakeyset.InvalidPage`.
