### ISSUE TITLE
Doesn't work with SQLAlchemy 1.4.0b1

### ISSUE THREAD

**Issue by sevanteri** [djrobstep/sqlakeyset#39]
`sqlalchemy.engine.result.RowProxy` is gone (thought wasn't actually even used in `paging.py`) and so is `sqlalchemy.util.lightweight_named_tuple`. Not sure if the lightweight namedtuple is moved somewhere else or if it's gone for good.

**Comment by acarapetis** [comment]
Thanks for the heads-up. I'll try to find some time to look at the changes in SQLAlchemy 1.4 soon.

**Comment by acarapetis** [comment]
New version with support for sqlalchemy1.4b1 is now live on PyPI - please try it out and report any issues! :)
