### ISSUE TITLE
Pagination not working with .desc()

### ISSUE THREAD

**Issue by mokrzesa** [djrobstep/sqlakeyset#41]
It seems that it is not possible to page query results while using `.desc()` or `desc(...)` I guess it would be extremely helpful.

**Comment by acarapetis** [comment]
Hi there,

[Our tests](https://github.com/djrobstep/sqlakeyset/blob/master/tests/test_paging.py) include examples using both `.desc()` and `desc(...)`. Could you provide a self-contained example demonstrating your problem?

Thanks

**Comment by mokrzesa** [comment]
@acarapetis Thank you very much for your quick response. After your message I've checked the tests and those do provide extensive coverage -  my case might actually be related to specifications of my query. If I won't be able to find solution regarding my implementation that would clearly distinguishing my problem from using `sqlakeyset` - I'll open a PR with additional test that would correspond to my case if that would be ok for you.

Thank you very much again and sorry for the inconvenience.
With best regards and greetings from Poland :poland:
