### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by lossyrob** [djrobstep/sqlakeyset#42]
the [packaging](https://pypi.org/project/packaging/) package is imported [here](https://github.com/djrobstep/sqlakeyset/blob/master/sqlakeyset/sqla.py#L2), but not declared in the package requirements.

I'm seeing a `ModuleNotFoundError` being thrown after the latest release in a project that uses `pip` for package management and `sqlalchemy`.

**Comment by acarapetis** [comment]
Thanks for the report - that was quick!

Looks like our CI tests didn't catch this because our dev-dependencies include `packaging`.

**Comment by acarapetis** [comment]
I've just merged the fix to master, new version should hit PyPI in a few minutes. Let me know if you have any further problems :)
