### ISSUE TITLE
Bookmark for every item in a page

### ISSUE THREAD

**Issue by MrSaints** [djrobstep/sqlakeyset#44]
Currently we can only retrieve the next or previous "bookmark".

As an extension of this, it would be nice to be able to retrieve the "bookmark" of every item in a page or have a utility function (I am unsure if one already exists?) to obtain the "bookmark" for a specific item in a page.

The use-case here is for satisfying Relay-style cursor pagination where every node has a unique cursor (see also https://github.com/photocrowd/django-cursor-pagination).

**Comment by acarapetis** [comment]
Thanks for your interest in the project :)

I think we already generate the bookmark tuples for every item in the page internally, there's just no publicly documented API for retrieving them. Should be easy to add, I'll try to find some time later to work on this.

**Comment by MrSaints** [comment]
@acarapetis Yeah, great work on the project. It works beautifully.

> I think we already generate the bookmark tuples for every item in the page internally

I was looking into it, but figured I'd log it here in case you already had a vision on how to approach it.

https://github.com/djrobstep/sqlakeyset/blob/6461dde11d88f76e3c65a2e059c884e376934f1b/sqlakeyset/results.py#L151
