### ISSUE TITLE
Support sqlalchemy 1.4.0

### ISSUE THREAD

**Issue by emattson** [djrobstep/sqlakeyset#45]
Pipenv breaks when trying to install with sqlalchemy >=1.4.0b1

**Comment by acarapetis** [comment]
Could you please provide some more information about the error you're getting and the version of sqlakeyset you're trying to install? Everything should work with 1.4.0b since #40 was merged.

**Comment by acarapetis** [comment]
Our CI tests now cover both sqlalchemy 1.3 and 1.4. Please re-open this with more details if you're still having issues.
