### ISSUE TITLE
SQLite compatibility

### ISSUE THREAD

**Issue by grignards** [djrobstep/sqlakeyset#48]
`sqlakeyset` uses the `row()` function which is not supported by SQLite. Using row values `(name1, name2)` in the comparison should also be possible and is supported by most database systems:

- [In MySQL](https://dev.mysql.com/doc/refman/8.0/en/expressions.html)
- [In PostgreSQL](https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-ROW-CONSTRUCTORS)
- [In SQLite](https://sqlite.org/rowvalue.html)

**Comment by acarapetis** [comment]
@djrobstep, what are your thoughts on this? Tests on the PR all pass, but I'm not familiar enough with the subtleties of row constructors and tuples in various SQL dialects to know if there could be any hidden gotchas here.

**Comment by djrobstep** [comment]
As far as I'm aware these should both do the same thing, so I don't see any issues with changing to tuples.
