### ISSUE TITLE
Custom binding logic issue

### ISSUE THREAD

**Issue by sebastiandev** [djrobstep/sqlakeyset#55]
Hi! I have and issue when the library is trying to get the associated dialect when doing `get_page`

We have a custom session that deals with a read and write engine, so we can lock to a write when needed. This switch is doen by overriding the `get_bind` method based on some context. 

The problem is that the sqlalkeyset is [doing](https://github.com/djrobstep/sqlakeyset/blob/master/sqlakeyset/paging.py#L102)
```
if place:
 dialect = getattr(s, "bind", s).dialect
```

So that is returning None for us. I was able to fix that by doing
```
maker = sessionmaker(class_=ReadWriteSession, bind=metadata.bind)
sess = scoped_session(maker)
```
> Adding the bind param was the temporary solution 

The problem is that now it will always use the same bind. I think the sqlakeyset library should be calling the `get_bind` method instead so custom logic from custom sessions is executed.

This is kinda a blocker for us.

What do you think?

**Comment by acarapetis** [comment]
Hi @sebastiandev,

Sorry for the delay getting to this. I think you're right that `get_bind()` is the API we should be using. I'll hopefully have a fix out today :)
