### ISSUE TITLE
When paging backwards, page.paging.items() seems to misalign bookmarks and values

### ISSUE THREAD

**Issue by mattalbr** [djrobstep/sqlakeyset#66]
I'm using sqlakeyset to implement relay-style pagination in a strawberry graphql server, and I noticed that when paging backwards using items(), the bookmarks and values are iterating in opposite directions. Sorry in advance for the graphql noise, it's just the easiest way for me to demonstrate the bug since I already have it implemented and can copy-paste.

For example, first I iterate forwards like:
```graphql
{
  accounts(first: 5, order: [{col: FULL_NAME, orderType: ASC}]) {
    pageInfo{
      hasNextPage
      hasPreviousPage
    }
    edges {
      cursor
      node {
        fullName
      }
    }
  }
}
```

Results:
```json
{
  "data": {
    "accounts": {
      "pageInfo": {
        "hasNextPage": true,
        "hasPreviousPage": false,
      },
      "edges": [
        {
          "cursor": "s:Abel French~i:259",
          "node": {
            "fullName": "Abel French"
          }
        },
        {
          "cursor": "s:Abraham Banks~i:85",
          "node": {
            "fullName": "Abraham Banks"
          }
        },
        {
          "cursor": "s:Albert Ballard~i:28",
          "node": {
            "fullName": "Albert Ballard"
          }
        },
        {
          "cursor": "s:Alexis Carter~i:191",
          "node": {
            "fullName": "Alexis Carter"
          }
        },
        {
          "cursor": "s:Algae Mountain~i:120",
          "node": {
            "fullName": "Algae Mountain"
          }
        }
      ]
    }
  }
}
```

The `cursor` that I'm using is just `sqlakeyset.results.s.serialize_values(keyset)` where keyset is grabbed from `for (keyset, _), value in page.paging.items()`. If I then take one of those cursors and iterate backwards via `sqlakeyset.get_page(query, per_page=5, before=sqlakeyset.results.s.unserialize_values(cursor))`, e.g. on "s:Algae Mountain~i:120" above

I get:
```json
{
  "data": {
    "accounts": {
      "pageInfo": {
        "hasNextPage": true,
        "hasPreviousPage": false
      },
      "edges": [
        {
          "cursor": "s:Alexis Carter~i:191",
          "node": {
            "fullName": "Abel French"
          }
        },
        {
          "cursor": "s:Albert Ballard~i:28",
          "node": {
            "fullName": "Abraham Banks"
          }
        },
        {
          "cursor": "s:Abraham Banks~i:85",
          "node": {
            "fullName": "Albert Ballard"
          }
        },
        {
          "cursor": "s:Abel French~i:259",
          "node": {
            "fullName": "Alexis Carter"
          }
        }
      ]
    }
  }
}
```

Notice that the cursors (which are just keysets taken from page.paging.items()) are reversed relative to the values.

Maybe this is because I'm not encoding the `backwards` property of the bookmark in my cursor, but I wouldn't think that would matter. 

Please let me know if there's any additional information I can provide to help with debugging.

Versions:
sqlakeyset: 1.0.1650280980
sqlalchemy: 1.4.37
database: PostgreSQL 14

**Comment by acarapetis** [comment]
Thanks for the report! I didn't look too closely at the tests for the new `.items()` method, turns out we're testing for incorrect behaviour! I've got a fix in the pipeline now, will hopefully have a new release out soon.

**Comment by acarapetis** [comment]
New release should hit PyPI within an hour, please let us know if you have any further issues :)

**Comment by mattalbr** [comment]
Thanks for the super prompt fix!

**Comment by acarapetis** [comment]
@mattalbr Oh dear!

> Is it possible that we fetch an extra bookmark in order to check page before/after and when you just reversed markers in that PR, it's messing up the sentinel value?

Yup, dead on - tests only covered the case where there was no excess, i.e. the page went all the way to the end of the resultset. Fix incoming.

**Comment by mattalbr** [comment]
Confirmed on my end that our unit tests pass now! I'll let you know if we hit any more snags, but it seems as long as we avoid https://github.com/djrobstep/sqlakeyset/issues/54 everything is working smoothly. Thanks for the fast responses and the handy library!
