### ISSUE TITLE
ImportError: cannot import name 'LegacyRow' from 'sqlalchemy.engine.row'

### ISSUE THREAD

**Issue by reinhardt1053** [djrobstep/sqlakeyset#72]
Hello, 

I get the following error, which I guess is caused by SQLAlchemy >= 2.0:

`ImportError: cannot import name 'LegacyRow' from 'sqlalchemy.engine.row'`

Is there any workaround ? 

Versions:
```
SQLAlchemy==2.0.3
sqlakeyset==1.0.1659142803
```

**Comment by acarapetis** [comment]
Yeah, we have not yet updated sqlakeyset to work with sqlalchemy 2. If I ever find the time and motivation it's on my to-do list; but PRs are welcome!

**Comment by acarapetis** [comment]
Fixed in #77.
