### ISSUE TITLE
Question: Converting Page to Pydantic Model

### ISSUE THREAD

**Issue by josephlim75** [djrobstep/sqlakeyset#73]
How do I convert a db model returned from sqlakeyset page to a pydantic model ?  When I convert using `from_orm`, there isn't any error but it just get 1 empty record.  My solution now is to loop the `page` and append to the pydantic model manually.  But I wanted to use the `from_orm` out of the box without writing any custom mapping.  Is this possible ?

## Example code

```python
# Pydantic Model
class AppSchemaModel(BaseModel):
  customer_id: str
  field1: Optional[str] = None
  field2: Optional[str] = None
  field3: Optional[str] = None

  class Config:
      orm_mode = True

# SQLAlchemy model
class AppModel(Base):
  customer_id = Column(String(36))
  field1 = Column(String(50))
  field2 = Column(String(50))
  field3 = Column(String(50))
  created_date = Column(TIMESTAMP_TZ)


query = (
    db_session.query(AppModel)
    .filter(AppModel.customer_id == customer_id)
    .order_by(AppModel.created_date.desc())
)
page = get_page(query, per_page=5)

# The page returns 5 records successfully, but i want to convert the
# db model into pydantic.
data = AppSchemaModel.from_orm(page)
# data now contain 1 instead of 5 records but all the 4 fields are empty.

  
```

**Comment by acarapetis** [comment]
Would this work if `page` was instead a list of records obtained directly from the sqlalchemy query? From my recollection of pydantic you should be writing something like `[AppSchemaModel.from_orm(record) for record in page]`, or perhaps using `parse_obj_as` with `List[AppSchemaModel]`.

**Comment by acarapetis** [comment]
Closing this one, if my previous comment was mistaken please re-open.
