### ISSUE TITLE
Package status

### ISSUE THREAD

**Issue by j-walker23** [djrobstep/sqlakeyset#9]
Hey, thanks for the work on this. It's pretty cool.

This issue is to ask about the future. Sadly this package is the only keyset pagination lib for sqlalchemy i can find on the internets. And it also seems like you might be done with it (not judging, i know all about being too busy).

So i just wanted to verify your thoughts before i figure out my next strat.

Thanks.

**Comment by djrobstep** [comment]
Hey, glad you like it!

As you suggest, I am rather busy and I have a lot don't have the time to develop new features or enhancements for `sqlakeyset`, at this stage. However I would be delighted to receive pull requests for any new features or bugfixes, and would do the work to get them merged and released.

**Comment by j-walker23** [comment]
That's great. Managing PRs should always be enough. Thank you!

I have some monkey patch hacks i've used to get some queries to work like with hybrid_properties. I'll try and clean them up and push up a PR.

Any rules or guidlines you want to mention?

Thanks again.

**Comment by djrobstep** [comment]
Oh nice, looking forward to seeing it!

No real guidelines, other than making sure there's some basic tests for what you're adding/changing.

If you have any questions, just let me know!
