### ISSUE TITLE
asyncio paging returns tuples of length 1

### ISSUE THREAD

**Issue by cypai** [djrobstep/sqlakeyset#93]
I'm using the latest version of 2.0.1691149549.

When running the following code:
```
query = select(Something)
page = await select_page(session, query, page=page_token, per_page=limit)
```
I get a list of length-1 tuples instead of a list of ORM objects. Print shows:
```
[(<app.models.Something object at 0x106ff7580>,)]
```
This causes some issues with Pydantic's orm_mode validation.

I'm expecting to get:
```
[<app.models.Something object at 0x106ff7580>]
```

**Comment by acarapetis** [comment]
This is expected - you would get the same result from `await session.execute(query)`.

We could consider adding something like `select_scalar_page` analogous to `session.scalars` for convenience, but it's pretty easy to unwrap the results yourself:

```python
query = select(Something)
page = await select_page(session, query, page=page_token, per_page=limit)
results = [x for x, in page] # now feed results to pydantic
```
