### ISSUE TITLE
`row._mapping` is broken after pagination

### ISSUE THREAD

**Issue by sevanteri** [djrobstep/sqlakeyset#99]
Already found the culprit at https://github.com/djrobstep/sqlakeyset/blob/aa097fc055322ad0773d619115640f7b005152c8/sqlakeyset/sqla20.py#L105-L112

Instead of `key -> col value` mapping, `Row` wants `key -> col index` mapping.

I'm running SQLAlchemy 2.0.23 and I have no idea if something has changed after 2.0.11.

**Comment by acarapetis** [comment]
Thanks for the report!
